name: Build Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -f comfyui-docker/Dockerfile -t comfyui-custom comfyui-docker
        RUN git clone https://github.com/ssitu/ComfyUI-UseEverywhere-nodes /app/custom_nodes/ComfyUI-UseEverywhere-nodes
        RUN git clone https://github.com/TMElyralab/comfyui-save-image-with-meta /app/custom_nodes/comfyui-save-image-with-meta
        RUN git clone https://github.com/YourUsername/ComfyUI-Hunyuan3DWrapper /app/custom_nodes/ComfyUI-Hunyuan3DWrapper && \
            pip install -r /app/custom_nodes/ComfyUI-Hunyuan3DWrapper/requirements.txt && \
            pip install -e /app/custom_nodes/ComfyUI-Hunyuan3DWrapper && \
            cd /app/custom_nodes/ComfyUI-Hunyuan3DWrapper/hy3dgen/texgen/custom_rasterizer && \
            python3 setup.py install && \
            cd ../../differentiable_renderer && \
            python3 setup.py install
        RUN git clone https://github.com/ltdrdata/ComfyUI_IPAdapter_plus /app/custom_nodes/ComfyUI_IPAdapter_plus
        RUN git clone https://github.com/WASasquatch/ComfyUI-Custom-Scripts /app/custom_nodes/ComfyUI-Custom-Scripts
        RUN git clone https://github.com/ltdrdata/ComfyUI-Impact-Pack /app/custom_nodes/ComfyUI-Impact-Pack
        RUN git clone https://github.com/Kosinkadink/ComfyUI-KJNodes /app/custom_nodes/ComfyUI-KJNodes
        RUN git clone https://github.com/givenchan/ComfyUI_essentials /app/custom_nodes/ComfyUI_essentials
        RUN git clone https://github.com/dustysys/ComfyUI-Advanced-ControlNet /app/custom_nodes/ComfyUI-Advanced-ControlNet
        RUN git clone https://github.com/ltdrdata/ComfyUI-Impact-Subpack /app/custom_nodes/ComfyUI-Impact-Subpack
        RUN git clone https://github.com/BadCafeCode/ComfyUI-tensorop /app/custom_nodes/ComfyUI-tensorop
        RUN git clone https://github.com/Kijai/ComfyUI-Florence2 /app/custom_nodes/ComfyUI-Florence2
        RUN git clone https://github.com/Fannovel16/comfyui_controlnet_aux /app/custom_nodes/comfyui_controlnet_aux
        RUN git clone https://github.com/rgthree/rgthree-comfy /app/custom_nodes/rgthree-comfy
        RUN git clone https://github.com/Thr33HeadedMonkey/ComfyUI-segment-anything-2 /app/custom_nodes/ComfyUI-segment-anything-2

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag and Push Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/comfyui-custom
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        docker tag comfyui-custom $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
